const data = [
  {
    id: 1,
    make: 'Chevrolet',
    model: 'Cruz',
    year: '2006',
    image: require('../../assets/image1.png'),
  },
  {
    id: 2,
    make: 'Ford',
    model: 'Bronco',
    year: '2007',
    image: require('../../assets/image2.png'),
  },
  {
    id: 3,
    make: 'Honda',
    model: 'Accord',
    year: '1999',
    image: require('../../assets/image3.png'),
  },
  {
    id: 4,
    make: 'Kia',
    model: 'Sorento',
    year: '1991',
    image: require('../../assets/image4.png'),
  },
  {
    id: 5,
    make: 'Toyota',
    model: 'Rav4',
    year: '2021',
    image: require('../../assets/image5.png'),
  },
  {
    id: 6,
    make: 'BMW',
    model: 'X1',
    year: '2020',
    image: require('../../assets/image6.png'),
  },
  {
    id: 7,
    make: 'Jeep',
    model: 'Wrangler',
    year: '2019',
    image: require('../../assets/image7.png'),
  },
  {
    id: 8,
    make: 'Nissan',
    model: 'Altima',
    year: '2017',
    image: require('../../assets/image8.png'),
  },
  {
    id: 9,
    make: 'BMW',
    model: 'i8',
    year: '2043',
    image: require('../../assets/image1.png'),
  },
  {
    id: 10,
    make: 'BMW',
    model: 'i8',
    year: '2030',
    image: require('../../assets/image2.png'),
  },
  {
    id: 11,
    make: 'Audi',
    model: 'A4',
    year: '2022',
    image: require('../../assets/image3.png'),
  },
  {
    id: 12,
    make: 'Audi',
    model: 'A4',
    year: '2022',
    image: require('../../assets/image4.png'),
  },
  {
    id: 13,
    make: 'Buick',
    model: 'Verano',
    year: '2010',
    image: require('../../assets/image5.png'),
  },
  {
    id: 14,
    make: 'Buick',
    model: 'Verano',
    year: '2008',
    image: require('../../assets/image6.png'),
  },
  {
    id: 15,
    make: 'Buick',
    model: 'Verano',
    year: '2009',
    image: require('../../assets/image7.png'),
  },
  {
    id: 16,
    make: 'Buick',
    model: 'Verano',
    year: '2002',
    image: require('../../assets/image8.png'),
  },
];
export default data;
